/**
 * Country utilities for country codes and flag rendering
 */

/**
 * Mapping of country names and codes to ISO 3166-1 alpha-2 country codes
 * Used for fetching country flags from flagcdn.com
 * Includes all 249 countries and territories with common aliases
 */
const COUNTRY_CODE_MAP: Record<string, string> = {
  // Americas
  'Afghanistan': 'af', 'AF': 'af',
  'Albania': 'al', 'AL': 'al',
  'Algeria': 'dz', 'DZ': 'dz',
  'American Samoa': 'as', 'AS': 'as',
  'Andorra': 'ad', 'AD': 'ad',
  'Angola': 'ao', 'AO': 'ao',
  'Anguilla': 'ai', 'AI': 'ai',
  'Antarctica': 'aq', 'AQ': 'aq',
  'Antigua and Barbuda': 'ag', 'Antigua & Barbuda': 'ag', 'AG': 'ag',
  'Argentina': 'ar', 'AR': 'ar',
  'Armenia': 'am', 'AM': 'am',
  'Aruba': 'aw', 'AW': 'aw',
  'Australia': 'au', 'AU': 'au',
  'Austria': 'at', 'AT': 'at',
  'Azerbaijan': 'az', 'AZ': 'az',
  'Bahamas': 'bs', 'BS': 'bs',
  'Bahrain': 'bh', 'BH': 'bh',
  'Bangladesh': 'bd', 'BD': 'bd',
  'Barbados': 'bb', 'BB': 'bb',
  'Belarus': 'by', 'BY': 'by',
  'Belgium': 'be', 'BE': 'be',
  'Belize': 'bz', 'BZ': 'bz',
  'Benin': 'bj', 'BJ': 'bj',
  'Bermuda': 'bm', 'BM': 'bm',
  'Bhutan': 'bt', 'BT': 'bt',
  'Bolivia': 'bo', 'BO': 'bo',
  'Bonaire': 'bq', 'BQ': 'bq',
  'Bosnia and Herzegovina': 'ba', 'Bosnia & Herzegovina': 'ba', 'BA': 'ba',
  'Botswana': 'bw', 'BW': 'bw',
  'Bouvet Island': 'bv', 'BV': 'bv',
  'Brazil': 'br', 'BR': 'br',
  'British Virgin Islands': 'vg', 'Virgin Islands, British': 'vg', 'VG': 'vg',
  'Brunei': 'bn', 'BN': 'bn',
  'Bulgaria': 'bg', 'BG': 'bg',
  'Burkina Faso': 'bf', 'BF': 'bf',
  'Burundi': 'bi', 'BI': 'bi',
  'Cabo Verde': 'cv', 'Cape Verde': 'cv', 'CV': 'cv',
  'Cambodia': 'kh', 'KH': 'kh',
  'Cameroon': 'cm', 'CM': 'cm',
  'Canada': 'ca', 'CA': 'ca',
  'Caribbean Netherlands': 'bq',
  'Cayman Islands': 'ky', 'KY': 'ky',
  'Central African Republic': 'cf', 'CF': 'cf',
  'Chad': 'td', 'TD': 'td',
  'Chile': 'cl', 'CL': 'cl',
  'China': 'cn', 'CN': 'cn',
  'Colombia': 'co', 'CO': 'co',
  'Comoros': 'km', 'KM': 'km',
  'Congo': 'cg', 'CG': 'cg',
  'Congo (Democratic Republic)': 'cd', 'Congo, Democratic Republic of the': 'cd', 'CD': 'cd',
  'Cook Islands': 'ck', 'CK': 'ck',
  'Costa Rica': 'cr', 'CR': 'cr',
  'Cote d\'Ivoire': 'ci', 'Ivory Coast': 'ci', 'CI': 'ci',
  'Croatia': 'hr', 'HR': 'hr',
  'Cuba': 'cu', 'CU': 'cu',
  'Curacao': 'cw', 'CW': 'cw',
  'Cyprus': 'cy', 'CY': 'cy',
  'Czech Republic': 'cz', 'Czechia': 'cz', 'CZ': 'cz',
  'Denmark': 'dk', 'DK': 'dk',
  'Djibouti': 'dj', 'DJ': 'dj',
  'Dominica': 'dm', 'DM': 'dm',
  'Dominican Republic': 'do', 'DO': 'do',
  'Ecuador': 'ec', 'EC': 'ec',
  'Egypt': 'eg', 'EG': 'eg',
  'El Salvador': 'sv', 'SV': 'sv',
  'Equatorial Guinea': 'gq', 'GQ': 'gq',
  'Eritrea': 'er', 'ER': 'er',
  'Estonia': 'ee', 'EE': 'ee',
  'Eswatini': 'sz', 'Swaziland': 'sz', 'SZ': 'sz',
  'Ethiopia': 'et', 'ET': 'et',
  'Falkland Islands': 'fk', 'FK': 'fk',
  'Faroe Islands': 'fo', 'FO': 'fo',
  'Fiji': 'fj', 'FJ': 'fj',
  'Finland': 'fi', 'FI': 'fi',
  'France': 'fr', 'FR': 'fr',
  'French Antilles': 'gp',
  'French Guiana': 'gf', 'GF': 'gf',
  'French Polynesia': 'pf', 'PF': 'pf',
  'French Southern Territories': 'tf', 'TF': 'tf',
  'Gabon': 'ga', 'GA': 'ga',
  'Gambia': 'gm', 'GM': 'gm',
  'Georgia': 'ge', 'GE': 'ge',
  'Germany': 'de', 'DE': 'de',
  'Ghana': 'gh', 'GH': 'gh',
  'Gibraltar': 'gi', 'GI': 'gi',
  'Greece': 'gr', 'GR': 'gr',
  'Greenland': 'gl', 'GL': 'gl',
  'Grenada': 'gd', 'GD': 'gd',
  'Guadeloupe': 'gp', 'GP': 'gp',
  'Guam': 'gu', 'GU': 'gu',
  'Guatemala': 'gt', 'GT': 'gt',
  'Guernsey': 'gg', 'GG': 'gg',
  'Guinea': 'gn', 'GN': 'gn',
  'Guinea-Bissau': 'gw', 'GW': 'gw',
  'Guyana': 'gy', 'GY': 'gy',
  'Haiti': 'ht', 'HT': 'ht',
  'Heard Island and McDonald Islands': 'hm', 'HM': 'hm',
  'Honduras': 'hn', 'HN': 'hn',
  'Hong Kong': 'hk', 'HK': 'hk',
  'Hungary': 'hu', 'HU': 'hu',
  'Iceland': 'is', 'IS': 'is',
  'India': 'in', 'IN': 'in',
  'Indonesia': 'id', 'ID': 'id',
  'Iran': 'ir', 'IR': 'ir',
  'Iraq': 'iq', 'IQ': 'iq',
  'Ireland': 'ie', 'IE': 'ie',
  'Isle of Man': 'im', 'IM': 'im',
  'Israel': 'il', 'IL': 'il',
  'Italy': 'it', 'IT': 'it',
  'Jamaica': 'jm', 'JM': 'jm',
  'Japan': 'jp', 'JP': 'jp',
  'Jersey': 'je', 'JE': 'je',
  'Jordan': 'jo', 'JO': 'jo',
  'Kazakhstan': 'kz', 'KZ': 'kz',
  'Kenya': 'ke', 'KE': 'ke',
  'Kiribati': 'ki', 'KI': 'ki',
  'Korea': 'kr', 'South Korea': 'kr', 'KR': 'kr',
  'North Korea': 'kp', 'KP': 'kp',
  'Kosovo': 'xk', 'XK': 'xk',
  'Kuwait': 'kw', 'KW': 'kw',
  'Kyrgyzstan': 'kg', 'KG': 'kg',
  'Laos': 'la', 'LA': 'la',
  'Latvia': 'lv', 'LV': 'lv',
  'Lebanon': 'lb', 'LB': 'lb',
  'Lesotho': 'ls', 'LS': 'ls',
  'Liberia': 'lr', 'LR': 'lr',
  'Libya': 'ly', 'LY': 'ly',
  'Liechtenstein': 'li', 'LI': 'li',
  'Lithuania': 'lt', 'LT': 'lt',
  'Luxembourg': 'lu', 'LU': 'lu',
  'Macau': 'mo', 'MO': 'mo',
  'Madagascar': 'mg', 'MG': 'mg',
  'Malawi': 'mw', 'MW': 'mw',
  'Malaysia': 'my', 'MY': 'my',
  'Maldives': 'mv', 'MV': 'mv',
  'Mali': 'ml', 'ML': 'ml',
  'Malta': 'mt', 'MT': 'mt',
  'Marshall Islands': 'mh', 'MH': 'mh',
  'Martinique': 'mq', 'MQ': 'mq',
  'Mauritania': 'mr', 'MR': 'mr',
  'Mauritius': 'mu', 'MU': 'mu',
  'Mayotte': 'yt', 'YT': 'yt',
  'Mexico': 'mx', 'MX': 'mx',
  'Micronesia': 'fm', 'FM': 'fm',
  'Micronesia (Federated States of)': 'fm',
  'Moldova': 'md', 'MD': 'md',
  'Monaco': 'mc', 'MC': 'mc',
  'Mongolia': 'mn', 'MN': 'mn',
  'Montenegro': 'me', 'ME': 'me',
  'Montserrat': 'ms', 'MS': 'ms',
  'Morocco': 'ma', 'MA': 'ma',
  'Mozambique': 'mz', 'MZ': 'mz',
  'Myanmar': 'mm', 'Burma': 'mm', 'MM': 'mm',
  'Namibia': 'na', 'NA': 'na',
  'Nauru': 'nr', 'NR': 'nr',
  'Nepal': 'np', 'NP': 'np',
  'Netherlands': 'nl', 'NL': 'nl',
  'New Caledonia': 'nc', 'NC': 'nc',
  'New Zealand': 'nz', 'NZ': 'nz',
  'Nicaragua': 'ni', 'NI': 'ni',
  'Niger': 'ne', 'NE': 'ne',
  'Nigeria': 'ng', 'NG': 'ng',
  'Niue': 'nu', 'NU': 'nu',
  'Norfolk Island': 'nf', 'NF': 'nf',
  'North Macedonia': 'mk', 'MK': 'mk',
  'Northern Mariana Islands': 'mp', 'MP': 'mp',
  'Norway': 'no', 'NO': 'no',
  'Oman': 'om', 'OM': 'om',
  'Pakistan': 'pk', 'PK': 'pk',
  'Palau': 'pw', 'PW': 'pw',
  'Palestine': 'ps', 'PS': 'ps',
  'Palestinian Territories': 'ps',
  'Panama': 'pa', 'PA': 'pa',
  'Papua New Guinea': 'pg', 'PG': 'pg',
  'Paraguay': 'py', 'PY': 'py',
  'Peru': 'pe', 'PE': 'pe',
  'Philippines': 'ph', 'PH': 'ph',
  'Pitcairn Islands': 'pn', 'PN': 'pn',
  'Poland': 'pl', 'PL': 'pl',
  'Portugal': 'pt', 'PT': 'pt',
  'Puerto Rico': 'pr', 'PR': 'pr',
  'Qatar': 'qa', 'QA': 'qa',
  'Reunion': 're', 'RE': 're',
  'Romania': 'ro', 'RO': 'ro',
  'Russia': 'ru', 'Russian Federation': 'ru', 'RU': 'ru',
  'Rwanda': 'rw', 'RW': 'rw',
  'Saint Barthélemy': 'bl', 'BL': 'bl',
  'Saint Helena': 'sh', 'SH': 'sh',
  'Saint Kitts and Nevis': 'kn', 'Saint Kitts & Nevis': 'kn', 'KN': 'kn',
  'Saint Lucia': 'lc', 'LC': 'lc',
  'Saint Martin': 'mf', 'MF': 'mf',
  'Saint Martin (French part)': 'mf',
  'Saint Pierre and Miquelon': 'pm', 'PM': 'pm',
  'Saint Pierre & Miquelon': 'pm',
  'Saint Vincent and the Grenadines': 'vc', 'Saint Vincent & the Grenadines': 'vc', 'VC': 'vc',
  'Samoa': 'ws', 'WS': 'ws',
  'San Marino': 'sm', 'SM': 'sm',
  'Sao Tome and Principe': 'st', 'Sao Tome & Principe': 'st', 'ST': 'st',
  'Saudi Arabia': 'sa', 'SA': 'sa',
  'Senegal': 'sn', 'SN': 'sn',
  'Serbia': 'rs', 'RS': 'rs',
  'Seychelles': 'sc', 'SC': 'sc',
  'Sierra Leone': 'sl', 'SL': 'sl',
  'Singapore': 'sg', 'SG': 'sg',
  'Sint Maarten': 'sx', 'SX': 'sx',
  'Slovakia': 'sk', 'SK': 'sk',
  'Slovenia': 'si', 'SI': 'si',
  'Solomon Islands': 'sb', 'SB': 'sb',
  'Somalia': 'so', 'SO': 'so',
  'South Africa': 'za', 'ZA': 'za',
  'South Georgia and the South Sandwich Islands': 'gs', 'GS': 'gs',
  'South Sudan': 'ss', 'SS': 'ss',
  'Spain': 'es', 'ES': 'es',
  'Sri Lanka': 'lk', 'LK': 'lk',
  'Sudan': 'sd', 'SD': 'sd',
  'Suriname': 'sr', 'SR': 'sr',
  'Svalbard and Jan Mayen': 'sj', 'SJ': 'sj',
  'Sweden': 'se', 'SE': 'se',
  'Switzerland': 'ch', 'CH': 'ch',
  'Syria': 'sy', 'SY': 'sy',
  'Taiwan': 'tw', 'TW': 'tw',
  'Tajikistan': 'tj', 'TJ': 'tj',
  'Tanzania': 'tz', 'TZ': 'tz',
  'Thailand': 'th', 'TH': 'th',
  'Timor-Leste': 'tl', 'East Timor': 'tl', 'TL': 'tl',
  'Togo': 'tg', 'TG': 'tg',
  'Tokelau': 'tk', 'TK': 'tk',
  'Tonga': 'to', 'TO': 'to',
  'Trinidad and Tobago': 'tt', 'Trinidad & Tobago': 'tt', 'TT': 'tt',
  'Tunisia': 'tn', 'TN': 'tn',
  'Turkey': 'tr', 'TR': 'tr',
  'Turkmenistan': 'tm', 'TM': 'tm',
  'Turks and Caicos Islands': 'tc', 'TC': 'tc',
  'Tuvalu': 'tv', 'TV': 'tv',
  'Uganda': 'ug', 'UG': 'ug',
  'Ukraine': 'ua', 'UA': 'ua',
  'United Arab Emirates': 'ae', 'UAE': 'ae', 'AE': 'ae',
  'United Kingdom': 'gb', 'UK': 'gb', 'GB': 'gb',
  'United States': 'us', 'USA': 'us', 'US': 'us',
  'Uruguay': 'uy', 'UY': 'uy',
  'US Virgin Islands': 'vi', 'Virgin Islands, U.S.': 'vi', 'VI': 'vi',
  'Uzbekistan': 'uz', 'UZ': 'uz',
  'Vanuatu': 'vu', 'VU': 'vu',
  'Vatican City': 'va', 'Holy See': 'va', 'VA': 'va',
  'Venezuela': 've', 'VE': 've',
  'Vietnam': 'vn', 'VN': 'vn',
  'Wallis and Futuna': 'wf', 'WF': 'wf',
  'Wallis and Futuna Islands': 'wf',
  'Western Sahara': 'eh', 'EH': 'eh',
  'Yemen': 'ye', 'YE': 'ye',
  'Zambia': 'zm', 'ZM': 'zm',
  'Zimbabwe': 'zw', 'ZW': 'zw',
};

/**
 * Get ISO 3166-1 alpha-2 country code from country name or code
 * @param country Country name or code (e.g., "United States", "US", "USA")
 * @returns Two-letter country code in lowercase (e.g., "us") or null if not found
 */
export function getCountryCode(country: string | null | undefined): string | null {
  if (!country) return null;
  
  // Try exact match first
  const exactMatch = COUNTRY_CODE_MAP[country];
  if (exactMatch) return exactMatch;
  
  // Try case-insensitive match as fallback
  const lowerCountry = country.toLowerCase();
  for (const [key, value] of Object.entries(COUNTRY_CODE_MAP)) {
    if (key.toLowerCase() === lowerCountry) {
      return value;
    }
  }
  
  return null;
}

/**
 * Get flag URL from flagcdn.com for a given country
 * @param country Country name or code
 * @param size Flag size - 'w20', 'w40', 'w80', 'w160', 'w320', 'w640', 'w1280'
 * @returns Flag URL or null if country code not found
 */
export function getFlagUrl(country: string | null | undefined, size: 'w20' | 'w40' | 'w80' | 'w160' | 'w320' | 'w640' | 'w1280' = 'w40'): string | null {
  const code = getCountryCode(country);
  if (!code) return null;
  return `https://flagcdn.com/${size}/${code}.png`;
}

/**
 * Get all country code mappings
 * Useful for preview/testing purposes
 */
export function getCountryCodeMapping(): Record<string, string> {
  return { ...COUNTRY_CODE_MAP };
}
