/**
 * Theme utilities
 *
 * Icon and color mappings for investment themes generated by the backend.
 */

import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  Atom,
  BadgeDollarSign,
  Banknote,
  Battery,
  BatteryCharging,
  Binoculars,
  Blocks,
  Bot,
  Brain,
  BrainCircuit,
  BrainCog,
  Briefcase,
  Building2,
  Cable,
  Car,
  CarFront,
  ChartCandlestick,
  ChartLine,
  Cloud,
  Code,
  Coins,
  Cpu,
  CreditCard,
  Database,
  Dna,
  Droplets,
  Eye,
  Factory,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  Fuel,
  Gamepad2,
  Gem,
  Globe,
  HelpCircle,
  Hospital,
  Landmark,
  Leaf,
  Lightbulb,
  LockKeyhole,
  MemoryStick,
  Microchip,
  Microscope,
  Network,
  Orbit,
  Package,
  PersonStanding,
  PlaneTakeoff,
  Plug,
  Radar,
  Radiation,
  RadioTower,
  RefreshCw,
  Rocket,
  Route,
  Satellite,
  SatelliteDish,
  ScanEye,
  Server,
  Shield,
  ShieldCheck,
  ShieldHalf,
  ShoppingCart,
  Stethoscope,
  Store,
  Sun,
  TentTree,
  TestTube,
  Truck,
  UtilityPole,
  Video,
  WandSparkles,
  Warehouse,
  Wind,
  Zap,
} from 'lucide-react'

export const THEME_ICONS: Record<string, LucideIcon> = {
  // AI & Compute
  'AI Infrastructure': BrainCircuit,
  'Generative AI': WandSparkles,
  'AI Agents': Bot,
  'AI Software': BrainCog,
  'Sovereign AI': Flag,
  'Data Centers': Server,
  'Accelerated Computing': Zap,
  'GPU Computing': Cpu,
  'Edge Computing': Network,

  // Semis
  'Chip Design': Microchip,
  'Semiconductor Equipment': Factory,
  'Foundry Ecosystem': Blocks,
  'Advanced Packaging': Package,
  'Memory & Storage': MemoryStick,
  'Photonics': Lightbulb,
  'Optical Interconnects': Cable,

  // Quantum
  'Quantum Computing': Atom,
  'Quantum Networking': Orbit,
  'Quantum Security': LockKeyhole,

  // Cybersecurity
  'Cybersecurity': Shield,
  'Identity Security': Fingerprint,
  'Zero Trust': ShieldCheck,
  'Observability': Eye,
  'Threat Intelligence': Radar,

  // Cloud & Software
  'Cloud Infrastructure': Cloud,
  'Enterprise SaaS': Building2,
  'Developer Platforms': Code,
  'Data Analytics': Database,
  'Digital Transformation': RefreshCw,

  // Robotics & Automation
  'Humanoid Robotics': PersonStanding,
  'Industrial Robotics': Bot,
  'Warehouse Automation': Warehouse,
  'Machine Vision': ScanEye,
  'Industrial Automation': Factory,
  'Sensors & LiDAR': Radar,

  // Mobility
  'Autonomous Vehicles': Car,
  'Electric Vehicles': CarFront,
  'Battery Technology': Battery,
  'Charging Infrastructure': Plug,
  'Mobility Platforms': Route,

  // Defense
  'Defense Tech': ShieldHalf,
  'Military AI': Brain,
  'ISR & Surveillance': Binoculars,
  'Drones / UAV': PlaneTakeoff,
  'Electronic Warfare': RadioTower,

  // Space
  'Launch Services': Rocket,
  'Satellites': Satellite,
  'Space Infrastructure': SatelliteDish,
  'Space Communications': Orbit,

  // Energy
  'Nuclear': Radiation,
  'SMR': Atom,
  'Uranium': Fuel,
  'Grid Infrastructure': UtilityPole,
  'Power Generation': Zap,
  'Battery Storage': BatteryCharging,
  'Solar': Sun,
  'Wind': Wind,
  'Hydrogen': FlaskConical,
  'Carbon Capture': Leaf,
  'Oil & Gas': Flame,
  'LNG': Droplets,

  // Finance
  'Fintech': BadgeDollarSign,
  'Digital Banking': Landmark,
  'Payments': CreditCard,
  'Asset Management': ChartLine,
  'Capital Markets': ChartCandlestick,
  'Crypto Infrastructure': Blocks,
  'Digital Assets': Coins,

  // Healthcare
  'Drug Discovery': Microscope,
  'Biologics': TestTube,
  'Gene Therapy': Dna,
  'Precision Medicine': Stethoscope,
  'Diagnostics': FlaskRound,
  'Medical Devices': Activity,
  'Healthcare Services': Hospital,

  // Consumer
  'Gaming': Gamepad2,
  'E-commerce': ShoppingCart,
  'Digital Advertising': BadgeDollarSign,
  'Streaming': Video,
  'Social Media': Globe,
  'Consumer Brands': Store,
  'Luxury': Gem,
  'Travel & Leisure': TentTree,

  // Industrial
  'Logistics': Truck,
  'Supply Chain': Network,
  'Construction Technology': Building2,
  'Infrastructure': UtilityPole,
  'Industrial Machinery': Factory,

  // Materials
  'Rare Earths': Gem,
  'Critical Minerals': FlaskConical,
  'Lithium': Battery,
  'Copper': Cable,
  'Gold': Coins,
  'Silver': Banknote,

  // Telecom
  'Telecommunications': RadioTower,
  '5G Infrastructure': Network,
  'Fiber Networks': Cable,

  // Real Estate
  'Data Center REITs': Server,
  'Industrial REITs': Warehouse,
  'Residential REITs': Building2,
  'Healthcare REITs': Hospital,

  // Fallbacks
  'Unclassified': HelpCircle,
  'Unknown': HelpCircle,
  'Other': Briefcase,
}

export const THEME_TEXT_COLORS: Record<string, string> = {
  // AI & Compute
  'AI Infrastructure': 'text-violet-600 dark:text-violet-400',
  'Generative AI': 'text-fuchsia-600 dark:text-fuchsia-400',
  'AI Agents': 'text-purple-600 dark:text-purple-400',
  'AI Software': 'text-indigo-600 dark:text-indigo-400',
  'Sovereign AI': 'text-blue-700 dark:text-blue-400',
  'Data Centers': 'text-blue-600 dark:text-blue-400',
  'Accelerated Computing': 'text-sky-600 dark:text-sky-400',
  'GPU Computing': 'text-cyan-600 dark:text-cyan-400',
  'Edge Computing': 'text-teal-600 dark:text-teal-400',

  // Semis
  'Chip Design': 'text-orange-600 dark:text-orange-400',
  'Semiconductor Equipment': 'text-amber-600 dark:text-amber-400',
  'Foundry Ecosystem': 'text-yellow-700 dark:text-yellow-400',
  'Advanced Packaging': 'text-lime-700 dark:text-lime-400',
  'Memory & Storage': 'text-emerald-600 dark:text-emerald-400',
  'Photonics': 'text-pink-600 dark:text-pink-400',
  'Optical Interconnects': 'text-rose-600 dark:text-rose-400',

  // Quantum
  'Quantum Computing': 'text-cyan-700 dark:text-cyan-300',
  'Quantum Networking': 'text-blue-700 dark:text-blue-300',
  'Quantum Security': 'text-indigo-700 dark:text-indigo-300',

  // Cybersecurity
  'Cybersecurity': 'text-red-600 dark:text-red-400',
  'Identity Security': 'text-rose-600 dark:text-rose-400',
  'Zero Trust': 'text-orange-700 dark:text-orange-400',
  'Observability': 'text-slate-600 dark:text-slate-400',
  'Threat Intelligence': 'text-red-700 dark:text-red-300',

  // Cloud & Software
  'Cloud Infrastructure': 'text-sky-600 dark:text-sky-400',
  'Enterprise SaaS': 'text-blue-600 dark:text-blue-400',
  'Developer Platforms': 'text-indigo-600 dark:text-indigo-400',
  'Data Analytics': 'text-cyan-600 dark:text-cyan-400',
  'Digital Transformation': 'text-purple-600 dark:text-purple-400',

  // Robotics & Automation
  'Humanoid Robotics': 'text-violet-700 dark:text-violet-300',
  'Industrial Robotics': 'text-zinc-600 dark:text-zinc-400',
  'Warehouse Automation': 'text-stone-600 dark:text-stone-400',
  'Machine Vision': 'text-emerald-700 dark:text-emerald-300',
  'Industrial Automation': 'text-neutral-700 dark:text-neutral-300',
  'Sensors & LiDAR': 'text-lime-700 dark:text-lime-300',

  // Mobility
  'Autonomous Vehicles': 'text-blue-700 dark:text-blue-300',
  'Electric Vehicles': 'text-green-600 dark:text-green-400',
  'Battery Technology': 'text-lime-600 dark:text-lime-400',
  'Charging Infrastructure': 'text-emerald-600 dark:text-emerald-400',
  'Mobility Platforms': 'text-teal-700 dark:text-teal-300',

  // Defense
  'Defense Tech': 'text-slate-700 dark:text-slate-300',
  'Military AI': 'text-zinc-700 dark:text-zinc-300',
  'ISR & Surveillance': 'text-stone-700 dark:text-stone-300',
  'Drones / UAV': 'text-sky-700 dark:text-sky-300',
  'Electronic Warfare': 'text-indigo-700 dark:text-indigo-300',

  // Space
  'Launch Services': 'text-indigo-600 dark:text-indigo-400',
  'Satellites': 'text-blue-600 dark:text-blue-400',
  'Space Infrastructure': 'text-violet-600 dark:text-violet-400',
  'Space Communications': 'text-cyan-700 dark:text-cyan-300',

  // Energy
  'Nuclear': 'text-yellow-600 dark:text-yellow-400',
  'SMR': 'text-amber-600 dark:text-amber-400',
  'Uranium': 'text-lime-700 dark:text-lime-300',
  'Grid Infrastructure': 'text-blue-700 dark:text-blue-300',
  'Power Generation': 'text-orange-600 dark:text-orange-400',
  'Battery Storage': 'text-green-600 dark:text-green-400',
  'Solar': 'text-amber-500 dark:text-amber-300',
  'Wind': 'text-teal-600 dark:text-teal-400',
  'Hydrogen': 'text-cyan-600 dark:text-cyan-400',
  'Carbon Capture': 'text-emerald-700 dark:text-emerald-300',
  'Oil & Gas': 'text-red-700 dark:text-red-400',
  'LNG': 'text-orange-700 dark:text-orange-30₀',

  // Finance
  'Fintech': 'text-emerald-600 dark:text-emerald-400',
  'Digital Banking': 'text-green-700 dark:text-green-300',
  'Payments': 'text-teal-700 dark:text-teal-300',
  'Asset Management': 'text-blue-700 dark:text-blue-300',
  'Capital Markets': 'text-indigo-700 dark:text-indigo-300',
  'Crypto Infrastructure': 'text-orange-600 dark:text-orange-400',
  'Digital Assets': 'text-yellow-600 dark:text-yellow-400',

  // Healthcare
  'Drug Discovery': 'text-rose-600 dark:text-rose-400',
  'Biologics': 'text-pink-600 dark:text-pink-400',
  'Gene Therapy': 'text-fuchsia-600 dark:text-fuchsia-400',
  'Precision Medicine': 'text-violet-600 dark:text-violet-400',
  'Diagnostics': 'text-cyan-700 dark:text-cyan-300',
  'Medical Devices': 'text-sky-700 dark:text-sky-300',
  'Healthcare Services': 'text-red-600 dark:text-red-400',

  // Consumer
  'Gaming': 'text-purple-600 dark:text-purple-400',
  'E-commerce': 'text-pink-600 dark:text-pink-400',
  'Digital Advertising': 'text-orange-600 dark:text-orange-400',
  'Streaming': 'text-red-600 dark:text-red-400',
  'Social Media': 'text-blue-600 dark:text-blue-400',
  'Consumer Brands': 'text-amber-700 dark:text-amber-300',
  'Luxury': 'text-yellow-700 dark:text-yellow-300',
  'Travel & Leisure': 'text-emerald-700 dark:text-emerald-300',

  // Industrial
  'Logistics': 'text-stone-700 dark:text-stone-300',
  'Supply Chain': 'text-slate-700 dark:text-slate-300',
  'Construction Technology': 'text-orange-700 dark:text-orange-300',
  'Infrastructure': 'text-neutral-700 dark:text-neutral-300',
  'Industrial Machinery': 'text-zinc-700 dark:text-zinc-300',

  // Materials
  'Rare Earths': 'text-orange-700 dark:text-orange-300',
  'Critical Minerals': 'text-amber-700 dark:text-amber-300',
  'Lithium': 'text-lime-700 dark:text-lime-300',
  'Copper': 'text-orange-600 dark:text-orange-400',
  'Gold': 'text-yellow-600 dark:text-yellow-300',
  'Silver': 'text-slate-500 dark:text-slate-300',

  // Telecom
  'Telecommunications': 'text-cyan-700 dark:text-cyan-300',
  '5G Infrastructure': 'text-blue-700 dark:text-blue-300',
  'Fiber Networks': 'text-sky-700 dark:text-sky-300',

  // Real Estate
  'Data Center REITs': 'text-indigo-700 dark:text-indigo-300',
  'Industrial REITs': 'text-stone-700 dark:text-stone-300',
  'Residential REITs': 'text-emerald-700 dark:text-emerald-300',
  'Healthcare REITs': 'text-rose-700 dark:text-rose-300',

  'Unclassified': 'text-neutral-500 dark:text-neutral-400',
  'Unknown': 'text-neutral-500 dark:text-neutral-400',
  'Other': 'text-neutral-600 dark:text-neutral-400',
}

export const THEME_HEX_COLORS: Record<string, string> = {
  'AI Infrastructure': '#8b5cf6',
  'Generative AI': '#d946ef',
  'AI Agents': '#9333ea',
  'AI Software': '#4f46e5',
  'Sovereign AI': '#1d4ed8',
  'Data Centers': '#2563eb',
  'Accelerated Computing': '#0284c7',
  'GPU Computing': '#0891b2',
  'Edge Computing': '#0f766e',
  'Chip Design': '#ea580c',
  'Semiconductor Equipment': '#d97706',
  'Foundry Ecosystem': '#a16207',
  'Advanced Packaging': '#65a30d',
  'Memory & Storage': '#059669',
  'Photonics': '#db2777',
  'Optical Interconnects': '#e11d48',
  'Quantum Computing': '#0e7490',
  'Quantum Networking': '#1d4ed8',
  'Quantum Security': '#4338ca',
  'Cybersecurity': '#dc2626',
  'Identity Security': '#e11d48',
  'Zero Trust': '#c2410c',
  'Observability': '#475569',
  'Threat Intelligence': '#b91c1c',
  'Cloud Infrastructure': '#0284c7',
  'Enterprise SaaS': '#2563eb',
  'Developer Platforms': '#4f46e5',
  'Data Analytics': '#0891b2',
  'Digital Transformation': '#9333ea',
  'Humanoid Robotics': '#6d28d9',
  'Industrial Robotics': '#52525b',
  'Warehouse Automation': '#57534e',
  'Machine Vision': '#047857',
  'Industrial Automation': '#404040',
  'Sensors & LiDAR': '#4d7c0f',
  'Autonomous Vehicles': '#1d4ed8',
  'Electric Vehicles': '#16a34a',
  'Battery Technology': '#65a30d',
  'Charging Infrastructure': '#059669',
  'Mobility Platforms': '#0f766e',
  'Defense Tech': '#334155',
  'Military AI': '#3f3f46',
  'ISR & Surveillance': '#44403c',
  'Drones / UAV': '#0369a1',
  'Electronic Warfare': '#4338ca',
  'Launch Services': '#4f46e5',
  'Satellites': '#2563eb',
  'Space Infrastructure': '#7c3aed',
  'Space Communications': '#0e7490',
  'Nuclear': '#ca8a04',
  'SMR': '#d97706',
  'Uranium': '#4d7c0f',
  'Grid Infrastructure': '#1d4ed8',
  'Power Generation': '#ea580c',
  'Battery Storage': '#16a34a',
  'Solar': '#f59e0b',
  'Wind': '#0d9488',
  'Hydrogen': '#0891b2',
  'Carbon Capture': '#047857',
  'Oil & Gas': '#b91c1c',
  'LNG': '#c2410c',
  'Fintech': '#059669',
  'Digital Banking': '#15803d',
  'Payments': '#0f766e',
  'Asset Management': '#1d4ed8',
  'Capital Markets': '#4338ca',
  'Crypto Infrastructure': '#f97316',
  'Digital Assets': '#eab308',
  'Drug Discovery': '#e11d48',
  'Biologics': '#db2777',
  'Gene Therapy': '#c026d3',
  'Precision Medicine': '#7c3aed',
  'Diagnostics': '#0e7490',
  'Medical Devices': '#0369a1',
  'Healthcare Services': '#dc2626',
  'Gaming': '#9333ea',
  'E-commerce': '#db2777',
  'Digital Advertising': '#ea580c',
  'Streaming': '#dc2626',
  'Social Media': '#2563eb',
  'Consumer Brands': '#b45309',
  'Luxury': '#a16207',
  'Travel & Leisure': '#047857',
  'Logistics': '#44403c',
  'Supply Chain': '#334155',
  'Construction Technology': '#c2410c',
  'Infrastructure': '#404040',
  'Industrial Machinery': '#3f3f46',
  'Rare Earths': '#c2410c',
  'Critical Minerals': '#b45309',
  'Lithium': '#4d7c0f',
  'Copper': '#ea580c',
  'Gold': '#eab308',
  'Silver': '#64748b',
  'Telecommunications': '#0e7490',
  '5G Infrastructure': '#1d4ed8',
  'Fiber Networks': '#0369a1',
  'Data Center REITs': '#4338ca',
  'Industrial REITs': '#57534e',
  'Residential REITs': '#047857',
  'Healthcare REITs': '#be123c',
  'Unclassified': '#9ca3af',
  'Unknown': '#9ca3af',
  'Other': '#737373',
}

export function getThemeIcon(theme: string | null | undefined): LucideIcon {
  if (!theme) return HelpCircle
  return THEME_ICONS[theme] || Briefcase
}

export function getThemeColor(theme: string | null | undefined): string {
  if (!theme) return 'text-neutral-500 dark:text-neutral-400'
  return THEME_TEXT_COLORS[theme] || 'text-neutral-600 dark:text-neutral-400'
}

export function getThemeHexColor(theme: string | null | undefined): string {
  if (!theme) return '#9ca3af'
  return THEME_HEX_COLORS[theme] || '#737373'
}

export function getAllThemes(): string[] {
  return Object.keys(THEME_ICONS)
    .filter((theme) => theme !== 'Unknown' && theme !== 'Other')
    .sort()
}