name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # Use manifest config for monorepo support
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  # Optional: Notify on release
  notify-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Created
        run: |
          echo "Release ${{ needs.release-please.outputs.tag_name }} was created!"
          echo "Docker images will be built automatically by docker-build.yml workflow"
